// Flat ESLint config. Prettier owns formatting — `eslint-config-prettier` is
// last so it switches off every stylistic rule the two would otherwise fight
// over, leaving ESLint to judge correctness only.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import vitest from "@vitest/eslint-plugin";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      "coverage/**",
      // Generated by `pnpm build` and committed because the runner needs it —
      // linting it would report esbuild's output as if someone wrote it. One
      // bundle per duty, so the pattern has to match at every depth: the root
      // listing's `dist/`, and `translate/dist/` beside its `action.yml`.
      "**/dist/**",
      // Dogfood CLI tools outside src/ are not in the tsconfig project, so
      // eslint cannot resolve their types. The canonical conformance code
      // lives in src/duties/dependa/conformance/ which IS linted.
      "dogfood/**",
    ],
  },

  js.configs.recommended,

  // TypeScript, linted with type information. `projectService` hands the parser
  // the same program `tsc` builds, which is what makes the rules below possible
  // at all: a floating promise or an unawaited thenable is invisible to a
  // parser that only sees syntax. This action is almost entirely async I/O
  // against a model provider and the GitHub API, so that is the class of bug it
  // is most exposed to.
  {
    files: ["**/*.ts", "**/*.mts", "**/*.cts"],
    extends: [tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // `verbatimModuleSyntax` erases nothing it was not told to erase, so a
      // type imported without the `type` keyword becomes a real runtime import.
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      // Every value crossing into this process is untrusted or unvalidated: an
      // action input, a provider's JSON, a thread body. Parsing it into a real
      // type is this codebase's central job, so the rules that report an
      // unchecked `any` flowing onward are the ones worth keeping loudest.
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
    },
  },

  // Plain ESM JavaScript — this config and the build script. No tsconfig covers
  // them, so the type-aware rules have no program to consult and are switched
  // off explicitly rather than left to fail at parse time.
  {
    files: ["**/*.mjs", "**/*.js"],
    extends: [tseslint.configs.disableTypeChecked],
    rules: {
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },

  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      // Everything here runs on Node, on the Actions runner. There is no
      // browser context anywhere in this repository.
      globals: { ...globals.node, ...globals.es2024 },
    },
    rules: {
      // An action communicates through `@actions/core`, which writes the
      // workflow commands that produce log grouping, annotations and secret
      // masking. A bare `console.log` bypasses all three — including the
      // masking, which is the one that matters when an api key is in scope.
      "no-console": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "prefer-const": "error",
      "no-var": "error",
    },
  },

  {
    files: ["src/**/*.ts"],
    rules: {
      "@typescript-eslint/explicit-module-boundary-types": "error",
    },
  },

  // Tests. These rules catch the two ways a suite reports green for something
  // nobody ran — a focused test that silences its siblings, and a skipped one
  // that silences itself — plus assertions that can never fail.
  {
    files: ["src/**/*.test.ts", "src/**/*.integration.test.ts"],
    plugins: { vitest },
    rules: {
      ...vitest.configs.recommended.rules,
      "vitest/no-focused-tests": "error",
      "vitest/no-disabled-tests": "error",
      "vitest/expect-expect": "error",
      "vitest/valid-expect": "error",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/unbound-method": "off",
    },
  },

  // The build script is invoked from a terminal, where what it writes to stdout
  // is its entire output.
  {
    files: ["tools/**/*.mjs", "*.config.{ts,mts,mjs}", "eslint.config.mjs"],
    rules: { "no-console": "off" },
  },

  prettier,
);
