/**
 * The Go manager — discovers dependencies from `go.mod`.
 *
 * Deterministic: the same `go.mod` content produces the same `Dependency`
 * list every time. No LLM, no network.
 *
 * Go modules use a `go.mod` file with `require` directives:
 *   require (
 *       github.com/foo/bar v1.2.3
 *       golang.org/x/text v0.3.0
 *   )
 * or inline:
 *   require github.com/foo/bar v1.2.3
 *
 * The `go.sum` file serves as the lockfile, containing hashes for each
 * dependency version. This manager does not edit `go.sum` — it must be
 * regenerated by running `go mod tidy`.
 *
 * Go module versions always have a `v` prefix (`v1.2.3`). The `+incompatible`
 * suffix indicates a module that predates Go modules. Both are handled here.
 */
import type { Dependency, UpdateProposal } from "../model.js";
import type { Manager, ManagerId, ManagerResult } from "./types.js";

/** The Go manager identifier. */
const ID: ManagerId = "go";

/** Filenames the Go manager looks for. */
const MANIFEST_FILENAMES = ["go.mod"] as const;

export function createGoManager(): Manager {
  return {
    id: ID,
    ecosystem: "go",
    manifestFilenames: MANIFEST_FILENAMES,
    parse,
    applyUpdate,
  };
}

/**
 * Parse a `go.mod` file and return every dependency found.
 *
 * Reads `require` directives (both single-line and block form). Indirect
 * dependencies (marked `// indirect`) are discovered but flagged.
 */
function parse(
  manifestPath: string,
  manifestContent: string,
  lockfileContent: string | null,
): ManagerResult {
  const dependencies: Dependency[] = [];
  let partial = false;

  // Resolve locked versions from go.sum if available
  const lockedVersions = lockfileContent !== null ? parseGoSum(lockfileContent) : null;
  if (lockfileContent !== null && lockedVersions === null) {
    partial = true;
  }

  // Parse require directives
  const requireDirectives = parseRequireBlock(manifestContent);

  for (const { module, version, indirect } of requireDirectives) {
    // Go module versions include the "v" prefix — strip it for semver comparison
    const bareVersion = version.replace(/^v/, "").replace(/\+incompatible$/, "");
    const isIndirect = indirect;

    // Go modules don't have a separate constraint — the version in go.mod IS
    // both the constraint and the current version. When a newer version exists,
    // it's a straightforward version bump.
    const currentVersion = lockedVersions?.get(module) ?? bareVersion;

    dependencies.push({
      ecosystem: "go",
      name: module,
      constraint: bareVersion, // The version in go.mod acts as both constraint and resolved version
      currentVersion,
      manifestPath,
      dev: isIndirect, // Use dev flag to mark indirect dependencies
      manager: ID,
    });
  }

  return { manifestPath, dependencies, partial };
}

/**
 * Parse `require` directives from a `go.mod` file.
 *
 * Handles both forms:
 * - Single-line: `require github.com/foo/bar v1.2.3`
 * - Block form:
 *   ```
 *   require (
 *       github.com/foo/bar v1.2.3
 *       golang.org/x/text v0.3.0 // indirect
 *   )
 *   ```
 */
function parseRequireBlock(content: string): readonly {
  readonly module: string;
  readonly version: string;
  readonly indirect: boolean;
}[] {
  const results: { module: string; version: string; indirect: boolean }[] = [];
  const lines = content.split("\n");
  let inRequireBlock = false;

  for (const rawLine of lines) {
    const line = rawLine.trim();

    // Skip comments and empty lines
    if (line.startsWith("//") || line.length === 0) continue;

    // Detect require block start
    if (line === "require (") {
      inRequireBlock = true;
      continue;
    }

    // Detect block end
    if (inRequireBlock && line === ")") {
      inRequireBlock = false;
      continue;
    }

    // Single-line require
    if (line.startsWith("require ")) {
      const rest = line.slice(8).trim();
      const parsed = parseRequireEntry(rest);
      if (parsed !== null) results.push(parsed);
      continue;
    }

    // Entry inside require block
    if (inRequireBlock) {
      const parsed = parseRequireEntry(line);
      if (parsed !== null) results.push(parsed);
    }
  }

  return results;
}

/**
 * Parse a single require entry: `github.com/foo/bar v1.2.3` or `module v1.2.3 // indirect`
 */
function parseRequireEntry(
  line: string,
): { module: string; version: string; indirect: boolean } | null {
  // Remove trailing comments
  const withoutComment = line.replace(/\s*\/\/.*$/, "").trim();
  if (withoutComment.length === 0) return null;

  // Split into module path and version
  const parts = withoutComment.split(/\s+/);
  if (parts.length < 2) return null;

  const module = parts[0] ?? "";
  const version = parts[1] ?? "";

  if (module.length === 0 || version.length === 0) return null;

  // Check for indirect comment
  const indirect = line.includes("// indirect");

  return { module, version, indirect };
}

/**
 * Parse a `go.sum` file to extract resolved versions.
 *
 * go.sum format: `module version h1:hash` or `module version/go.mod h1:hash`
 * Each module-version pair may appear twice (once for the module, once for go.mod).
 */
function parseGoSum(content: string): Map<string, string> | null {
  const versions = new Map<string, string>();

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;

    // Format: module version h1:hash
    const parts = trimmed.split(/\s+/);
    if (parts.length < 3) continue;

    const module = parts[0] ?? "";
    const version = parts[1] ?? "";
    const hash = parts[2] ?? "";

    // A valid go.sum line has a hash starting with h1:
    if (!hash.startsWith("h1:")) continue;

    // Skip go.mod entries
    if (version.endsWith("/go.mod")) continue;

    // Strip v prefix for internal consistency
    const bareVersion = version.replace(/^v/, "");
    versions.set(module, bareVersion);
  }

  return versions.size > 0 ? versions : null;
}

/**
 * Apply an update to a `go.mod` file, returning the modified content.
 *
 * Replaces `module old-version` with `module new-version` in both
 * single-line and block-form `require` directives.
 *
 * Returns null when the old reference is not found in the file.
 */
function applyUpdate(manifestContent: string, proposal: UpdateProposal): string | null {
  const moduleName = proposal.dependency.name;
  const oldVersion = `v${proposal.currentVersion}`;
  const newVersion = `v${proposal.targetVersion}`;

  const lines = manifestContent.split("\n");
  const newLines: string[] = [];
  let replaced = false;

  for (const line of lines) {
    // Check if this line contains the module with its old version
    // Match patterns like:
    //   github.com/foo/bar v1.2.3
    //   github.com/foo/bar v1.2.3 // indirect
    const pattern = `${moduleName} ${oldVersion}`;
    if (line.includes(pattern)) {
      newLines.push(line.replace(pattern, `${moduleName} ${newVersion}`));
      replaced = true;
      continue;
    }

    newLines.push(line);
  }

  if (!replaced) return null;

  return newLines.join("\n");
}
