/**
 * The manager interface — how `dependa` discovers dependencies.
 *
 * Each manager knows how to parse one kind of manifest file. It receives the
 * file content as a string (already read through the Contents API), never a
 * checkout path, and it returns structured data — never a network call.
 *
 * Deterministic by construction: the same manifest content produces the same
 * Dependency list every time. No LLM, no network, no randomness.
 *
 * A new ecosystem adds one manager file and registers it in `registry.ts`.
 * No other module changes — the manager interface is already wide enough.
 */
import type { Ecosystem, Dependency, UpdateProposal } from "../model.js";

/**
 * The stable identifier for a manager. Part of the closed set — a name not
 * registered here is refused the same way an unknown Capability is.
 */
export type ManagerId = "npm" | "github-actions" | "cargo" | "go" | "docker" | "node-version";

/** What a manager discovered from one manifest file. */
export interface ManagerResult {
  /** The manifest path that was read. */
  readonly manifestPath: string;
  /** Every dependency found in this manifest. */
  readonly dependencies: readonly Dependency[];
  /**
   * Whether the read was partial — e.g. a lockfile was expected but could
   * not be read. A partial result is still usable; dependencies without a
   * `currentVersion` will be handled with extra caution downstream.
   */
  readonly partial: boolean;
}

/**
 * The abstraction for dependency discovery.
 *
 * Deterministic: same content in, same result out. No network, no model.
 */
export interface Manager {
  /** The stable identifier for this manager. */
  readonly id: ManagerId;
  /** The ecosystem this manager discovers dependencies for. */
  readonly ecosystem: Ecosystem;
  /**
   * Which filenames this manager looks for, in priority order.
   * e.g. `["package.json"]`, `["Cargo.toml"]`, `["go.mod"]`, `["Dockerfile"]`
   */
  readonly manifestFilenames: readonly string[];
  /**
   * Parses a manifest file's content and returns every dependency found.
   *
   * `lockfileContent` is null when no lockfile was found or it could not be
   * read. The manager should still return dependencies from the manifest;
   * they will carry an empty `currentVersion`.
   */
  parse(
    manifestPath: string,
    manifestContent: string,
    lockfileContent: string | null,
  ): ManagerResult;
  /**
   * Apply an update to a manifest file, returning the modified content.
   *
   * Deterministic: the same manifest content, the same proposal, and the
   * same constraint grammar produce the same output every time. No model
   * call is involved in producing the edit. If the edit does not validate,
   * it is dropped.
   *
   * Returns null when the update cannot be applied (e.g. the constraint
   * grammar is not one this manager knows how to rewrite).
   */
  applyUpdate(manifestContent: string, proposal: UpdateProposal): string | null;
  /**
   * Apply an update to a lockfile, returning the modified content.
   *
   * Returns null when the manager does not handle lockfiles, or when the
   * lockfile format does not support in-place version replacement (some
   * lockfiles must be regenerated by the package manager, not edited).
   */
  applyLockfileUpdate?(lockfileContent: string, proposal: UpdateProposal): string | null;
  /**
   * Custom manifest path matching for managers whose filenames are variable.
   *
   * When provided, `select()` calls this for every file in the tree that did
   * NOT match `manifestFilenames`. A return of `true` means the manager
   * claims the file as a manifest. This supports ecosystems like GitHub
   * Actions where workflow filenames are user-chosen and cannot be enumerated.
   *
   * When absent, only `manifestFilenames` is used — the default for every
   * ecosystem whose manifest name is fixed (npm, Cargo, Go, Docker).
   */
  matchManifest?(path: string): boolean;
}
